### ISSUE TITLE
Absolute webroot paths are not interpreted correctly

### ISSUE THREAD

**Issue by karilaa-dev** [akemin-dayo/BlueMapOfflineSkinSupport#1]
In config i type: /var/www/sBluemap
But it doesn't work and it creates a folder in the server directory
![image](https://user-images.githubusercontent.com/27882744/117539812-f4555680-b014-11eb-8f5c-a3845ef26de6.png)

**Comment by akemin-dayo** [comment]
BlueMapOfflineSkinSupport does not currently support absolute paths — I'll fix this in the next version (as well as add a toggle for the log output).

If you want a quick workaround for the time being, you can use symbolic links (`ln -s`).

That being said, I'm curious now — what's your `webroot` value set to in BlueMap's `render.conf` and `webserver.conf`?

**Comment by karilaa-dev** [comment]
> BlueMapOfflineSkinSupport does not currently support absolute paths — I'll fix this in the next version (as well as add a toggle for the log output).
> 
> If you want a quick workaround for the time being, you can use symbolic links (`ln -s`).
> 
> That being said, I'm curious now — what's your `webroot` value set to in BlueMap's `render.conf` and `webserver.conf`?

Webroot in render.conf and webserver.conf - [ ] same, is /var/www/sBluemap

**Comment by akemin-dayo** [comment]
Got it — I'll push out a new update with a fix for this issue soon.

**Comment by akemin-dayo** [comment]
This issue has been fixed as of version 1.1, which you can find [here](https://github.com/akemin-dayo/BlueMapOfflineSkinSupport/releases).
