### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MatadorProBr** [akemin-dayo/BlueMapOfflineSkinSupport#10]
I would like to know if the plugin still works? I'm using the plugin with SkinRestorer and it doesn't work.

Also the plugin seems to not have a api-version?
[org.bukkit.craftbukkit.v1_19_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
Legacy plugin BlueMapOfflineSkinSupport v1.3 does not specify an api-version.

**Comment by pelmentor** [comment]
Works for me on 1.19.3. Just need to change the path to maps/assets/playerheads or whatever the new path is for where bluemap stores player icons now. It occasionally gives warnings about mojang api connection down but still works.

**Comment by griverat** [comment]
On the latest minecraft version (1.20.1) with latest bluemap (3.14) I found that the `playerheads` folder used is not the one on the top level `assets` folder, i.e `bluemap/web/assets/playerheads` is no longer used for playerhead icons. Instead, each map has its own `assets/playerhead` folder, so for the `world` map the playerhead icons used should be located in `bluemap/web/maps/world/assets/playerheads`, and so on for the other default maps (`world_nether`, `world_the_end`) and any other custom map added.

In linux, the solution I came up with was to use a symbolic soft link for each `playerhead` folder inside `maps/assets/` that points to `bluemap/web/assets/playerheads/`. Basically, do this for each folder inside `maps`

```bash
# assuming you are in your server folder
cd bluemap/web/maps/world/assets

# this folder needs to exist bluemap/web/assets/playerheads
ln -s ../../../assets/playerheads .
```

**Comment by akemin-dayo** [comment]
BlueMapSkinSupport 3.0 and 2.0 have been released, which brings everything up to date.

https://github.com/akemin-dayo/BlueMapSkinSupport/releases
