### ISSUE TITLE
Consider changing the project name to something else.

### ISSUE THREAD

**Issue by akemin-dayo** [akemin-dayo/BlueMapOfflineSkinSupport#8]
The name "BlueMapOfflineSkinSupport" sort of seems to imply that it's only useful for offline-mode servers, when in reality it is actually useful for online-mode servers too (so player-defined custom skins will be shown).

That being said, I'm not really sure what _else_ to call it.

Will need more thought on this.

**Comment by Fefedu973** [comment]
I think you can rename it BluemapCustomSkinSupport and update the plugin for 1.18.2 and 1.19.2

**Comment by Fefedu973** [comment]
+ can you add support for v3 pls

**Comment by akemin-dayo** [comment]
BMOSS already works with 1.19.2 and 1.18.2. It's version-agnostic in that sense.

It also already works with BlueMap 3.3.
