### ISSUE TITLE
Internal error on 1.18.2

### ISSUE THREAD

**Issue by Fefedu973** [akemin-dayo/BlueMapOfflineSkinSupport#9]
in logs : [07:03:02] [Server thread/INFO]: [BlueMapOfflineSkinSupport] Fefe_du_973 joined the server! Calling writeTrueCompositedPlayerHeadForBukkitPlayerAsynchronousCallback()...
 in game : internal exception io.netty.handler.codec.decoderexception com.google.gson.jsonparseexception: don't know how to turn {} into a component

**Comment by akemin-dayo** [comment]
What's the full log say? This seems like BMOSS somehow got an empty JSON response while trying to get a given user's profile data…

**Comment by Fefedu973** [comment]
ok so this is the full log
[latest.log](https://github.com/akemin-dayo/BlueMapOfflineSkinSupport/files/9454594/latest.log)

**Comment by Fefedu973** [comment]
> What's the full log say? This seems like BMOSS somehow got an empty JSON response while trying to get a given user's profile data…

any idea ?
